# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Don't print a new line at the start of the prompt
add_newline = false

# timeout (node is slow unfortunately)
command_timeout = 10000

# Replace the "❯" symbol in the prompt with "➜"
#[character]      # The name of the module we are configuring is "character"
#success_symbol = "[➜](bold red)"
#vicmd_symbol = "[➜](bold green)"
#error_symbol = "[✗](bold red)"

right_format = """$time"""

[time]
disabled = false
